import { IMedia } from '@/interfaces/IMedia'
export const mediaList: IMedia[] = [
	{
		id: 1,
		title: 'El hoyo',
		image:
			'https://image.tmdb.org/t/p/original/yVPear63M3MRiDyrSf6wsFgzN3A.jpg',
		califications: 6,
		rate: 4.6,
		type: 'movie',
		date: '2019-03-20',
		genre: 'Ciencia Ficción, Suspenso, Thriller',
		age: '18+',
	},
	{
		id: 2,
		title: 'El juego del calamar 2',
		image: 'https://f.rpp-noticias.io/2024/11/27/1674491gdto4imwkaar6zmjpg.jpg',
		califications: 3,
		rate: 4.4,
		type: 'serie',
		date: '2024-11-01',
		genre: 'Drama, Thriller',
		age: '18+',
	},
	{
		id: 3,
		title: 'The Dark Knight',
		image:
			'https://image.tmdb.org/t/p/original/r9BQs8VaMziqG2pVD7mcS3ORCWd.jpg',
		califications: 6,
		rate: 4.8,
		type: 'movie',
		date: '2008-07-18',
		genre: 'Acción, Crimen, Drama',
		age: 'A partir de 13 años',
	},
	{
		id: 4,
		view: true,
		title: 'Game of Thrones',
		image: 'https://www.el-parnasillo.com/juegotronos/juego-tronos-poster.jpg',
		califications: 6,
		rate: 3.7,
		type: 'serie',
		date: '2011-04-17',
		genre: 'Aventura, Drama, Fantasía',
		age: '18+',
	},
	{
		id: 5,
		title: 'Inception',
		image: 'https://flxt.tmsimg.com/assets/p7825626_p_v8_af.jpg',
		califications: 6,
		rate: 4.9,
		type: 'movie',
		date: '2010-07-16',
		genre: 'Acción, Ciencia Ficción, Suspenso',
		age: 'A partir de 13 años',
	},
	{
		id: 6,
		title: 'The Witcher',
		image:
			'https://www.lavanguardia.com/files/content_image_mobile_filter/uploads/2019/07/01/5fa532527f848.jpeg',
		califications: 6,
		rate: 3.9,
		type: 'serie',
		date: '2019-12-20',
		genre: 'Aventura, Drama, Fantasía',
		age: '16+',
	},
	{
		id: 7,
		title: 'Interstellar',
		image:
			'https://i.pinimg.com/originals/11/1c/5c/111c5c9ad99661af2d80e38948cf29d8.jpg',
		califications: 6,
		rate: 4.7,
		type: 'movie',
		date: '2014-11-07',
		genre: 'Aventura, Ciencia Ficción, Drama',
		age: 'A partir de 13 años',
	},
	{
		id: 8,
		title: 'Peaky Blinders',
		image: 'https://mx.web.img2.acsta.net/pictures/22/03/03/01/13/1621246.jpg',
		califications: 6,
		rate: 4.5,
		type: 'serie',
		date: '2013-09-12',
		genre: 'Crimen, Drama',
		age: '16+',
	},
	{
		id: 9,
		title: 'Avatar',
		image:
			'https://i.pinimg.com/originals/29/d5/d1/29d5d1246a102323071a986afe09e987.png',
		califications: 6,
		rate: 3.8,
		type: 'movie',
		date: '2009-12-18',
		genre: 'Acción, Aventura, Ciencia Ficción',
		age: 'A partir de 13 años',
	},
	{
		id: 10,
		title: 'The Mandalorian',
		image:
			'https://www.starwarsnewsnet.com/wp-content/uploads/2023/01/TheMandalorian_Poster_Season3.jpg',
		califications: 6,
		rate: 4.6,
		type: 'serie',
		date: '2019-11-12',
		genre: 'Acción, Aventura, Ciencia Ficción',
		age: 'ATP',
	},
	{
		id: 11,
		title: 'The Boys',
		image: 'https://es.web.img3.acsta.net/pictures/20/08/05/09/15/4715259.jpg',
		califications: 6,
		rate: 4.3,
		type: 'serie',
		date: '2019-07-26',
		genre: 'Acción, Comedia, Crimen',
		age: '18+',
	},
	{
		id: 12,
		title: 'Avengers: Endgame',
		image:
			'https://lumiere-a.akamaihd.net/v1/images/avengers_endgame_eng_p71_hd_2000x2818_961af0dc.png?region=0,0,2000,2818',
		califications: 6,
		rate: 4.2,
		type: 'movie',
		date: '2019-04-26',
		genre: 'Acción, Aventura, Ciencia Ficción',
		age: 'A partir de 13 años',
	},
	{
		id: 13,
		title: 'Better Call Saul',
		image:
			'https://visualprint-store.com/cdn/shop/products/uY1XPB7S5YPaz4Q7Bw2Zx8CgmPp.jpg?v=1668704185',
		califications: 6,
		rate: 4.9,
		type: 'serie',
		date: '2015-02-08',
		genre: 'Crimen, Drama',
		age: '16+',
	},
	{
		id: 14,
		title: 'Dune',
		image:
			'https://image.tmdb.org/t/p/original/AqjrlcNRSKx84CeNJyNueg6V1SR.jpg',
		califications: 6,
		rate: 4.1,
		type: 'movie',
		date: '2021-10-22',
		genre: 'Aventura, Ciencia Ficción, Drama',
		age: 'A partir de 13 años',
	},
	{
		id: 15,
		title: 'The Office',
		image: 'https://www.formulatv.com/images/series/posters/100/173/dest_1.jpg',
		califications: 6,
		rate: 4.8,
		type: 'serie',
		date: '2005-03-24',
		genre: 'Comedia',
		age: 'A partir de 13 años',
	},
	{
		id: 16,
		title: 'Friends',
		image: 'https://images.justwatch.com/poster/138458684/s718/friends.jpg',
		califications: 61,
		rate: 4.7,
		type: 'serie',
		date: '1994-09-22',
		genre: 'Comedia, Drama, Romance',
		age: '16+',
	},
	{
		id: 17,
		title: 'Sherlock',
		image: 'https://picfiles.alphacoders.com/355/thumb-1920-355468.jpg',
		califications: 66,
		rate: 4.9,
		type: 'serie',
		date: '2010-07-25',
		genre: 'Crimen, Drama, Misterio',
		age: 'A partir de 13 años',
	},
	{
		id: 18,
		title: 'Doctora Cha',
		image:
			'https://i.pinimg.com/736x/ea/4b/e9/ea4be9691e2526da0d7c4aa595e1ca53.jpg',
		califications: 22,
		rate: 4.2,
		type: 'serie',
		date: '2023-03-14',
		genre: 'Drama, Romance',
		age: 'A partir de 13 años',
	},
	{
		id: 19,
		title: 'Los simuladores',
		image:
			'https://img-cinear.test.dcarsat.com.ar/image/569d3a28b981283dad36d830/context/odeon_afiche_prod',
		califications: 12,
		rate: 4.5,
		type: 'serie',
		date: '2002-06-07',
		genre: 'Comedia, Drama, Suspenso',
		age: '16+',
	},
	{
		id: 20,
		title: 'Black Mirror',
		image:
			'https://www.dolby.com/siteassets/xf-site/content-detail-pages/bmboxshot_1280x1920_en.jpg',
		califications: 6,
		rate: 4.4,
		type: 'serie',
		date: '2011-12-04',
		genre: 'Ciencia Ficción, Drama, Suspenso',
		age: '16+',
	},
	{
		id: 21,
		title: 'The Last of Us',
		image:
			'https://areajugones.sport.es/wp-content/uploads/2022/11/the-last-of-us.jpeg',
		califications: 6,
		rate: 4.9,
		type: 'serie',
		date: '2023-01-15',
		genre: 'Drama, Ciencia Ficción, Terror',
		age: '18+',
	},
	{
		id: 22,
		title: 'Arcane',
		image:
			'https://static1.cbrimages.com/wordpress/wp-content/uploads/2024/08/arcane-season-2-key-visual.jpg',
		califications: 71,
		rate: 4.8,
		type: 'serie',
		date: '2021-11-06',
		genre: 'Acción, Aventura, Fantasía',
		age: '16+',
	},
	{
		id: 23,
		title: 'One Piece',
		image:
			'https://areajugones.sport.es/wp-content/uploads/2019/09/OnePiecePoster.jpg',
		califications: 13,
		rate: 4.5,
		type: 'serie',
		date: '1999-10-20',
		genre: 'Aventura, Acción, Fantasía',
		age: 'ATP',
	},
	{
		id: 24,
		title: 'Attack on Titan',
		image: 'https://m.media-amazon.com/images/I/717i6zTCpFL._AC_SL1000_.jpg',
		califications: 32,
		rate: 4.9,
		type: 'serie',
		date: '2013-04-07',
		genre: 'Acción, Ciencia Ficción, Drama',
		age: '16+',
	},
	{
		id: 25,
		view: true,
		title: 'Death Note',
		image:
			'https://image.tmdb.org/t/p/original/qDhbGqjZ7yFwa7FMIzuiQTQMfEQ.jpg',
		califications: 44,
		rate: 4.8,
		type: 'serie',
		date: '2006-10-03',
		genre: 'Crimen, Drama, Misterio',
		age: '16+',
	},
	{
		id: 26,
		title: 'Stranger Things',
		image: 'https://msgt.com.sg/wp-content/uploads/2023/06/MSGT-ST2.jpg',
		califications: 6,
		rate: 4.4,
		type: 'serie',
		date: '2016-07-15',
		genre: 'Ciencia Ficción, Terror',
		age: '16+',
	},
	{
		id: 27,
		title: 'Daredevil',
		image: 'https://ociotime.com/wp-content/uploads/2018/11/Daredevil.png',
		califications: 51,
		rate: 4.3,
		type: 'serie',
		date: '2015-04-10',
		genre: 'Acción, Crimen, Drama',
		age: '16+',
	},
	{
		id: 28,
		title: 'House of the Dragon',
		image:
			'https://www.dodmagazine.es/wp-content/uploads/2019/10/house-of-the-dragon.jpg',
		califications: 16,
		rate: 4.5,
		type: 'serie',
		date: '2022-08-21',
		genre: 'Aventura, Drama, Fantasía',
		age: '18+',
	},
	{
		id: 29,
		title: 'The 8 Show',
		image:
			'https://motchilltv.art/storage/images/the-8-show/the-8-show-thumb.jpg',
		califications: 77,
		rate: 4.2,
		type: 'serie',
		date: '2023-04-01',
		genre: 'Comedia, Drama',
		age: 'A partir de 13 años',
	},
	{
		id: 30,
		view: true,
		title: 'The 100',
		image:
			'https://i.pinimg.com/originals/2e/b5/b3/2eb5b318f8758c202e84802bd8bde2d0.jpg',
		califications: 6,
		rate: 4.4,
		type: 'serie',
		date: '2014-03-19',
		genre: 'Ciencia Ficción, Drama',
		age: 'A partir de 13 años',
	},
]

export const formatearFecha = (fecha: Date) => {
	return fecha
		.toLocaleString('es-ES', {
			weekday: 'long',
			year: 'numeric',
			month: 'long',
			day: 'numeric',
			hour: '2-digit',
			minute: '2-digit',
			hour12: true,
		})
		.replace(' a. m.', ' AM')
		.replace(' p. m.', ' PM')
}
